### ISSUE TITLE
Android binary

### ISSUE THREAD

**Issue by weedy** [andreiw/superalign#1]
I'm having trouble building this arm native. I'm not very good at this so I may have made a mistake, is it possible?

```
NDK_ROOT=~/projects/android-crosscompile/android-ndk-r9
export PATH="$NDK_ROOT/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/:$PATH"
export SYS_ROOT="$NDK_ROOT/platforms/android-14/arch-arm/"
export CC="arm-linux-androideabi-gcc --sysroot=$SYS_ROOT"
export LD="arm-linux-androideabi-ld"
export AR="arm-linux-androideabi-ar"
export RANLIB="arm-linux-androideabi-ranlib"
export STRIP="arm-linux-androideabi-strip"
export LDFLAGS=--sysroot=$SYS_ROOT
export CFLAGS=--sysroot=$SYS_ROOT

superalign $ make clean; make
rm -f sa sa.o dev.o stats.o
arm-linux-androideabi-gcc -O2 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -g2 --sysroot=/home/weedy/projects/android-crosscompile/android-ndk-r9/platforms/android-14/arch-arm/   -c -o sa.o sa.c
arm-linux-androideabi-gcc -O2 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -g2 --sysroot=/home/weedy/projects/android-crosscompile/android-ndk-r9/platforms/android-14/arch-arm/   -c -o dev.o dev.c
dev.c: In function 'time_read':
dev.c:90:3: warning: implicit declaration of function 'pread64' [-Wimplicit-function-declaration]
dev.c: In function 'time_write':
dev.c:116:3: warning: implicit declaration of function 'pwrite64' [-Wimplicit-function-declaration]
arm-linux-androideabi-gcc -O2 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -g2 --sysroot=/home/weedy/projects/android-crosscompile/android-ndk-r9/platforms/android-14/arch-arm/   -c -o stats.o stats.c
stats.c: In function 'stats_print':
stats.c:138:3: warning: implicit declaration of function 'sqrtl' [-Wimplicit-function-declaration]
stats.c:138:40: warning: incompatible implicit declaration of built-in function 'sqrtl' [enabled by default]
arm-linux-androideabi-gcc -lrt -lm --sysroot=/home/weedy/projects/android-crosscompile/android-ndk-r9/platforms/android-14/arch-arm/  sa.o dev.o stats.o   -o sa
/home/weedy/projects/android-crosscompile/android-ndk-r9/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lrt
/home/weedy/projects/android-crosscompile/android-ndk-r9/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: dev.o: in function time_read:dev.c:90: error: undefined reference to 'pread64'
/home/weedy/projects/android-crosscompile/android-ndk-r9/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: dev.o: in function time_write:dev.c:116: error: undefined reference to 'pwrite64'
/home/weedy/projects/android-crosscompile/android-ndk-r9/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: stats.o: in function stats_print:stats.c:138: error: undefined reference to 'sqrtl'
collect2: ld returned 1 exit status
make: *** [sa] Error 1
```

**Comment by andreiw** [comment]
Sorry for the late response.

The compile messages claim to not be able to find librt.so. (that's the
cannot find -lrt message). You need to use -Lyour/path (see man gcc) to
pass the right library paths) and verify that your build env is sane.

A

2013/8/6 weedy notifications@github.com

> I'm having trouble building this arm native. I'm not very good at this so
> I may have made a mistake, is it possible?
> 
> NDK_ROOT=~/projects/android-crosscompile/android-ndk-r9
> export PATH="$NDK_ROOT/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/:$PATH"
> export SYS_ROOT="$NDK_ROOT/platforms/android-14/arch-arm/"
> export CC="arm-linux-androideabi-gcc --sysroot=$SYS_ROOT"
> export LD="arm-linux-androideabi-ld"
> export AR="arm-linux-androideabi-ar"
> export RANLIB="arm-linux-androideabi-ranlib"
> export STRIP="arm-linux-androideabi-strip"
> export LDFLAGS=--sysroot=$SYS_ROOT
> export CFLAGS=--sysroot=$SYS_ROOT
> 
> superalign $ make clean; make
> rm -f sa sa.o dev.o stats.o
> arm-linux-androideabi-gcc -O2 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -g2 --sysroot=/home/weedy/projects/android-crosscompile/android-ndk-r9/platforms/android-14/arch-arm/   -c -o sa.o sa.c
> arm-linux-androideabi-gcc -O2 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -g2 --sysroot=/home/weedy/projects/android-crosscompile/android-ndk-r9/platforms/android-14/arch-arm/   -c -o dev.o dev.c
> dev.c: In function 'time_read':
> dev.c:90:3: warning: implicit declaration of function 'pread64' [-Wimplicit-function-declaration]
> dev.c: In function 'time_write':
> dev.c:116:3: warning: implicit declaration of function 'pwrite64' [-Wimplicit-function-declaration]
> arm-linux-androideabi-gcc -O2 -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -g2 --sysroot=/home/weedy/projects/android-crosscompile/android-ndk-r9/platforms/android-14/arch-arm/   -c -o stats.o stats.c
> stats.c: In function 'stats_print':
> stats.c:138:3: warning: implicit declaration of function 'sqrtl' [-Wimplicit-function-declaration]
> stats.c:138:40: warning: incompatible implicit declaration of built-in function 'sqrtl' [enabled by default]
> arm-linux-androideabi-gcc -lrt -lm --sysroot=/home/weedy/projects/android-crosscompile/android-ndk-r9/platforms/android-14/arch-arm/  sa.o dev.o stats.o   -o sa
> /home/weedy/projects/android-crosscompile/android-ndk-r9/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lrt
> /home/weedy/projects/android-crosscompile/android-ndk-r9/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: dev.o: in function time_read:dev.c:90: error: undefined reference to 'pread64'
> /home/weedy/projects/android-crosscompile/android-ndk-r9/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: dev.o: in function time_write:dev.c:116: error: undefined reference to 'pwrite64'
> /home/weedy/projects/android-crosscompile/android-ndk-r9/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: stats.o: in function stats_print:stats.c:138: error: undefined reference to 'sqrtl'
> collect2: ld returned 1 exit status
> make: **\* [sa] Error 1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/andreiw/superalign/issues/1
> .

## 

A
